name: mumo1
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - gcc_linux-64=12
  - gxx_linux-64=12
  - cuda-toolkit=12.8
  - cudnn
  - pytorch=2.5.1
  - torchvision=0.20.*
  - torchaudio=2.5.*
  - pip
  - pip:
      - pydantic~=2.11
      - numpy~=2.2
      - tokenizers~=0.20
      - torch-geometric~=2.6
      - pyarrow~=21.0
      - pydantic_core~=2.33
      - ogb~=1.3
      - wandb~=0.21
      - scipy~=1.15
      - regex~=2024.11
      - pandas~=2.2
      - joblib~=1.5
      - urllib3~=2.4
      - accelerate~=0.27
      - huggingface-hub~=0.32
      - packaging~=25.0
      - triton~=3.1
      - pillow~=11.0
      - mpmath~=1.3
      - attrs~=25.3
      - ninja~=1.11.1
      - gitdb~=4.0
      - Jinja2~=3.1
      - tqdm~=4.67
      - transformers~=4.45
      - multidict~=6.4
      - requests~=2.32
      - rdkit~=2025.3
      - safetensors~=0.5
      - multiprocess~=0.70
      - deepspeed~=0.17
      - pytz~=2025.2
      - datasets~=4.0
      - PyYAML~=6.0
      - matplotlib~=3.10
      - importlib_metadata~=8.0
      - platformdirs~=4.2
      - typing_extensions~=4.12
      - scikit-learn
